# Generated by Django 2.2 on 2022-05-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220522_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sell')], max_length=10, null=True),
        ),
    ]
