# Generated by Django 2.2 on 2022-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='40.765710', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='-73.976150', max_length=200),
        ),
    ]
