# Generated by Django 2.2 on 2022-05-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePassword',
        ),
        migrations.DeleteModel(
            name='ChangePasswordCode',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='pro_ny6h2o.png', upload_to=''),
        ),
    ]
